# Generated by Django 3.2.4 on 2021-07-09 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_alter_team_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(default=1)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.CharField(max_length=255)),
                ('client_org_number', models.CharField(blank=True, max_length=255, null=True)),
                ('client_address_number1', models.CharField(blank=True, max_length=255, null=True)),
                ('client_address_number2', models.CharField(blank=True, max_length=255, null=True)),
                ('client_zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('client_place', models.CharField(blank=True, max_length=255, null=True)),
                ('client_country', models.CharField(blank=True, max_length=255, null=True)),
                ('client_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('client_contact_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit note')], default='invoice', max_length=20)),
                ('due_days', models.IntegerField(default=14)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('is_credit_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_invoices', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='team.team')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Item',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=255)),
        #         ('quantity', models.IntegerField(default=1)),
        #         ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
        #         ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
        #         ('vat_rate', models.IntegerField(default=0)),
        #         ('discount', models.IntegerField(default=0)),
        #         ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='invoices.invoice')),
        #     ],
        # ),
    ]
