# Generated by Django 3.2.4 on 2021-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210714_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
