# Generated by Django 3.2.4 on 2021-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
