# Generated by Django 3.2.4 on 2021-07-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210716_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='zipcde',
            new_name='zipcode',
        ),
    ]
